# generated by datamodel-codegen:
#   filename:  SequenceRunLibraryLinkingChange.schema.json
#   timestamp: 2025-07-09T16:34:49+00:00

from __future__ import annotations

from datetime import datetime
from typing import List, Optional

from pydantic import BaseModel, Field


class SequenceRunLibraryLinkingChange(BaseModel):
    instrumentRunId: str
    sequenceRunId: str
    timeStamp: str
    linkedLibraries: List[str]


class AWSEvent(BaseModel):
    id: Optional[str] = None
    region: Optional[str] = None
    resources: Optional[List[str]] = None
    source: str
    time: Optional[datetime] = None
    version: Optional[str] = None
    account: Optional[str] = None
    detail_type: str = Field(..., alias='detail_type')
    detail: SequenceRunLibraryLinkingChange
