# generated by datamodel-codegen:
#   filename:  SequenceRunLibraryLinkingUpdate.schema.json
#   timestamp: 2026-10-04T16:19:04+00:00

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field


class SequenceRunLibraryLinkingUpdate(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str | None = None
    version: str | None = None
    instrumentRunId: str
    sequenceRunId: str
    timeStamp: datetime
    linkedLibraries: list[str]


class AWSEvent(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str | None = None
    region: str | None = None
    resources: list[str] | None = None
    source: str
    time: datetime | None = None
    version: str | None = None
    account: str | None = None
    detail_type: str = Field(..., alias="detail-type")
    detail: SequenceRunLibraryLinkingUpdate
