# generated by datamodel-codegen:
#   filename:  SequenceRunStateChange.schema.json
#   timestamp: 2026-09-01T12:25:02+00:00

# NOTE: hand-added and dropped on the next `make schema-gen-srsc` run - the same
# explanation lives on that Makefile target. Two of its flags shape this output:
#   --output-datetime-class datetime      plain `datetime` instead of pydantic's
#       AwareDatetime, which rejects timestamps carrying no timezone.
#   --allow-population-by-field-name      the `populate_by_name=True` below, so
#       `AWSEvent(detail_type=...)` is accepted; by default only the `detail-type`
#       alias is. Input only - dumps still emit `detail_type` unless by_alias=True.

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field


class SequenceRunStateChange(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    version: str
    orcabusId: str
    instrumentRunId: str
    runVolumeName: str
    runFolderPath: str
    runDataUri: str
    sampleSheetName: str | None
    startTime: datetime
    endTime: datetime | None = None
    status: str
    stateCreatedBy: str | None = None


class AWSEvent(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str | None = None
    region: str | None = None
    resources: list[str] | None = None
    source: str
    time: datetime | None = None
    version: str | None = None
    account: str | None = None
    detail_type: str = Field(..., alias="detail-type")
    detail: SequenceRunStateChange
