# generated by datamodel-codegen:
#   filename:  SequenceRunSampleSheetChange.schema.json
#   timestamp: 2026-10-04T16:19:03+00:00

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field


class SequenceRunSampleSheetChange(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    version: str
    instrumentRunId: str
    sequenceRunId: str
    timeStamp: datetime
    sampleSheetName: str
    apiUrl: str
    checksum: str
    checksumType: str
    description: str | None = None


class AWSEvent(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str | None = None
    region: str | None = None
    resources: list[str] | None = None
    source: str
    time: datetime | None = None
    version: str | None = None
    account: str | None = None
    detail_type: str = Field(..., alias="detail-type")
    detail: SequenceRunSampleSheetChange
