# generated by datamodel-codegen:
#   filename:  SequenceRunSampleSheetChange.schema.json
#   timestamp: 2025-11-27T15:53:00+00:00

from __future__ import annotations

from datetime import datetime
from typing import List, Optional

from pydantic import BaseModel, Field

class SequenceRunSampleSheetChange(BaseModel):
    instrumentRunId: str
    sequenceRunId: str
    timeStamp: datetime
    sampleSheetName: str
    apiUrl: str
    checksum: str
    description: Optional[str] = None


class AWSEvent(BaseModel):
    id: Optional[str] = None
    region: Optional[str] = None
    resources: Optional[List[str]] = None
    source: str
    time: Optional[datetime] = None
    version: Optional[str] = None
    account: Optional[str] = None
    detail_type: str = Field(..., alias='detail_type')
    detail: SequenceRunSampleSheetChange
