# generated by datamodel-codegen:
#   filename:  SequenceRunSampleSheetUpdate.schema.json
#   timestamp: 2026-10-04T16:19:03+00:00

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field


class Comment(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    comment: str
    createdBy: str


class SequenceRunSampleSheetUpdate(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str | None = None
    version: str | None = None
    instrumentRunId: str
    sequenceRunId: str | None = None
    timeStamp: datetime
    sampleSheetName: str
    samplesheetBase64gz: str
    comment: Comment | None = None


class AWSEvent(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str | None = None
    region: str | None = None
    resources: list[str] | None = None
    source: str
    time: datetime | None = None
    version: str | None = None
    account: str | None = None
    detail_type: str = Field(..., alias="detail-type")
    detail: SequenceRunSampleSheetUpdate
