# Generated by Django 5.2.3 on 2025-07-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sequence_run_manager", "0007_samplesheet"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="sequence",
            name="check_run_folder_path_or_bssh_keys_not_null",
        ),
        migrations.AlterField(
            model_name="sequence",
            name="run_data_uri",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sequence",
            name="run_volume_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sequence",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sequence",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("STARTED", "Started"),
                    ("FAILED", "Failed"),
                    ("SUCCEEDED", "Succeeded"),
                    ("ABORTED", "Aborted"),
                    ("RESOLVED", "Resolved"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
