# Generated by Django 5.2.3 on 2025-07-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sequence_run_manager",
            "0008_remove_sequence_check_run_folder_path_or_bssh_keys_not_null_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="association_id",
            new_name="target_id",
        ),
        migrations.AddField(
            model_name="comment",
            name="target_type",
            field=models.CharField(
                choices=[("sequence", "Sequence"), ("sample_sheet", "Sample Sheet")],
                default="sequence",
                max_length=255,
            ),
        ),
    ]
