# Generated by Django 5.2.3 on 2025-11-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sequence_run_manager",
            "0009_rename_association_id_comment_target_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="sequence",
            name="sample_sheet_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="sequence",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("STARTED", "Started"),
                    ("FAILED", "Failed"),
                    ("SUCCEEDED", "Succeeded"),
                    ("ABORTED", "Aborted"),
                    ("RESOLVED", "Resolved"),
                    ("DEPRECATED", "Deprecated"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
