# Generated by Django 5.2.3 on 2025-11-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sequence_run_manager",
            "0010_alter_sequence_sample_sheet_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="samplesheet",
            name="sample_sheet_content_original",
            field=models.TextField(blank=True, null=True),
        ),
    ]
