# Generated by Django 5.2.11 on 2026-09-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sequence_run_manager", "0011_add_sample_sheet_content_original"),
    ]

    operations = [
        migrations.AddField(
            model_name="state",
            name="created_by",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
